using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler1.Problems {
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    /// find the sum of the even-valued terms.
    /// </summary>
    public static class EvenFibonacciNumbers {
        public static void SolveEvenFibonacci() {
            Console.ForegroundColor = ConsoleColor.Red;
            var summary = new StringBuilder("Problem 2: Even Fibonacci numbers\n\n");
            summary.AppendLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms.");
            summary.AppendLine("By starting with 1 and 2, the first 10 terms will be:\n");
            summary.AppendLine("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
            summary.AppendLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million");
            summary.AppendLine("find the sum of the even-valued terms\n\n");
            Console.Write(summary);

            // print answer
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("Answer\n");
            Console.Write(Answer());
        }

        private static int Answer() {
            var intA = 0;
            int intB = 1;
            int sum = 0;

            try {
                // Compute Fibonacci sequence.
                while(intB < 4000000) {
                    int temp = intA;
                    intA = intB;
                    intB = temp + intB;

                    if(intB % 2 == 0 && intB < 4000000)
                        sum += intB;
                }
            } catch(Exception xcptn) {
                Console.Write(xcptn);
            }
            return sum;
        }
    }
}
